### ISSUE TITLE
为什么不对同步的RouterResponse做json解析处理，而是直接返回json数据，mHasGet参数一直是false?

### ISSUE THREAD

**Issue by nickming** [SpinyTech/ModularizationArchitecture#2]
如果不是异步请求，那么mHasGet参数就一直是false，这算不算是bug？
`JAVA
public String get() throws Exception {
        if (mIsAsync) {
            mResultString = mAsyncResponse.get(mTimeOut, TimeUnit.MILLISECONDS);
            if (!mHasGet) {
                try {
                    JSONObject jsonObject = new JSONObject(mResultString);
                    this.mCode = jsonObject.getInt("code");
                    this.mMessage = jsonObject.getString("msg");
                    this.mData = jsonObject.getString("data");
                } catch (JSONException e) {
                    e.printStackTrace();
                }
                mHasGet = true;
            }
        }
        return mResultString;
    }
`

**Comment by SpinyTech** [comment]
确实是bug，已经修复并将版本更新到了0.2.1，谢谢你发现bug。
