### ISSUE TITLE
请问为什么要用PriorityLogicWrapper把Logic给包装起来？

### ISSUE THREAD

**Issue by 604481157** [SpinyTech/ModularizationArchitecture#6]
是为了排序吗？没有明白这一层的含义。望解答一下。

**Comment by SpinyTech** [comment]
一个是为了排序，第二个是为了在必要的进程中初始化。你可以看到，这个wrapper里面是不包含实例的，只有一个class类，当在必要的进程中，需要这部分逻辑，会根据class，来获取实例。
