### ISSUE TITLE
请问，项目中使用网络库或者orm的库，需要新建module封装处理吗

### ISSUE THREAD

**Issue by nodream007** [SpinyTech/ModularizationArchitecture#8]
请问，项目中使用网络库或者orm的库，需要新建module封装处理吗

**Comment by SpinyTech** [comment]
你可以将这些基础的功能封装到base module中，然后base module引用ma，然后所有的module再引用base

**Comment by nodream007** [comment]
目前我的想法是底层做个api的封装库，把请求和逻辑都处理了。有个问题就是，这个库也可以当做module来建立Provider开放能力集给其他module调用，这样会不会显得有点复杂，还是直接通过接口调用就可以

**Comment by SpinyTech** [comment]
像网络，存储这些很基础的api，个人建议是和ma一起做成base库调用接口就可以了，基本上每个模块都会用到。像利用网络，编写的一些例如上传下载、断点续传这样的功能库，可以用module来做。这块没有规定死一定都是用模块来。具体的力度划分，由架构者来制定。
